server:
  port: 8080

spring:
  resources:
    static-locations: "classpath:/static/"
                                     
okta:
  oauth2:
    issuer: {issuer}
    clientId: {clientId}
    clientSecret: {clientSecret}